"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var registroAutomotor_1 = require("./registroAutomotor");
var auto_1 = require("./auto");
var camion_1 = require("./camion");
var moto_1 = require("./moto");
var registro = new registroAutomotor_1.registroAutomotor('REGISTRO 1');
var auto = new auto_1.Auto('ABC123', '1997', 'Ford');
var camion = new camion_1.Camion('DFG456', '2001', 'Scania');
var moto = new moto_1.Moto('HIJ789', '2008', 'Yamaha');
var auto1 = new auto_1.Auto('ACB123', '1997', 'Ford');
var camion1 = new camion_1.Camion('DGF456', '2001', 'Scania');
var moto1 = new moto_1.Moto('HJI789', '2008', 'Yamaha');
var camionnuevo = new camion_1.Camion('DDF234', '2000', 'Ford');
registro.setAgregarVehiculo(auto, moto, camion);
registro.setAgregarVehiculo(auto1, moto1, camion1);
registro.modifiedVehiculo('DFG456', undefined, camionnuevo);
console.log(registro.getAgregarVehiculo());
console.log(registro.getAgregarVehiculo());
console.log(registro.darDeBaja('ABC123'));
